name: Deploy Website to S3

on:
  push:
    branches:
      - main 
env:
  nutrition_API_key: ${{ secrets.NUTRITION_API_KEY }}
  exercise_API_key: ${{ secrets.EXERCISE_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your project code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 

      # Sync files to S3 bucket
      - name: Sync website to S3
        run: |
          aws s3 sync ./ s3://deploycs375-dantesam --delete